---
abstract: unknown
author:
  - 'Shaylan Govind <shaylan.govind@oicr.on.ca>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shatterproof
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 0
  List::Util: 0
  POSIX: 0
  Statistics::Distributions: 1.02
  Switch: 0
version: 0.07
