--- #YAML:1.0
name:               Shatterproof
version:            0.11
abstract:           ~
author:
    - Shaylan Govind <shaylan.govind@oicr.on.ca>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       2
    JSON::XS:             2.3
    List::Util:           1
    POSIX:                1
    Statistics::Distributions:  1.02
    Test::Deep:           0
    Test::Exception:      0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
